### PR TITLE
Implement an automated test suite

### PR DESCRIPTION
**Pull request by franko**
Actually it does two things:
- allow using "lgsl" without installation by using LUA_INIT="@local_exec.lua" and with an ad-hoc modification in template files searching strategy
- implement a python script that performs all the tests located in the tests directory.

The tests are based on the output of each Lua script which is compared to an expected output. For numerical algorithms for the moment the approach is simple: output results with "%.8g" so that small rounding differences does not affect the output.

### CODE REVIEW

**Comment by ladc** [comment]
Thank you for the pull request! 

However, it doesn't solve the issue of how to compare floats, which was one of the main problems with the previous test suite in Lua.

Unfortunately the python script doesn't seem to work for me. I get an error:

```
Traceback (most recent call last):
  File "tests/test-output.py", line 41, in <module>
    process = subprocess.Popen([luajit_exec, fullname], stdout=subprocess.PIPE, stderr=subprocess.PIPE, env = {'LUA_INIT': "@local_exec.lua"})
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exceptioen
OSError: [Errno 2] No such file or directory
```

Where am I supposed to run this python script? And why python, if I may ask? I would vastly prefer to have the test suite in Lua as well. I don't think the added dependency on a test library or luafilesystem would be a problem (just for running the tests). I'll try to make a Lua version.

I'm wondering if the new loader and template changes could perhaps be circumvented by renaming "src" to "lgsl", and setting the  package.path (or LUA_PATH) so that it first looks locally ("./?/init.lua;./?.lua;;" or the like).

**Comment by ladc** [comment]
I wrote a Lua version here: https://gist.github.com/ladc/51c60481781b049f7222

**Comment by franko** [comment]
Hi Lesley,

I’m a little bit surprised by your reaction to the usage of a python script but no problems :-)

I was using python for some practical reasons since it is easily available on all systems and all the useful modules are available out-of-the-box and are very complete.

Just one more remark: the usage of a python script for the testing suite does not introduce a dependency on python. It will be needed only by the developers to perform the tests but the user does not need to have python. In addition on linux box python is _always_ installed except in very special configurations.

In any case for me is fine to use Lua for the script. I’ve given a look at your script and it looks ok. It seems you are missing the “popen” function available in python from the subprocess module but I see that you have found an alternative solution.

**Comment by franko** [comment]
Talking about the problem of comparing floating point numbers, I’ve actually proposed a solution: compare numbers by using their string representations obtained with “%.8g” format by default. Depending on the test the precision can be changed. I believe this should be a good starting point and we can refine our approach later if we feels we need something better.

A few notes about the merits of the current tests.

In the non-linear fit test, we are actually checking that after 20 iterations the algorithm converge to the exact solution with 8 significant digit for each component. This looks a quite fair test to me since it does ensure that the code:
-   does not fail
-   the NL fit does actually converge
-   the result is close to the expected values within a “fair” precision (8 significant digits).

In the integration test I use the same simple-minded approach. As a special case one integration test should yield a result equal to zero. In this case I have artificially added 0.1 to the result. This is probably not elegant but for it is a practical solution to the problem.

In any case I hope I didn’t stumble on a major blocking point like the past time ;)

**Comment by franko** [comment]
No idea about the error with python script! It seems that either the luajit executable or the Lua script ("fullname" variable in the script) does not exists but I don't have any idea why. A print statement:

```
print luajit_exec, fullname
```

could help.

**Comment by ladc** [comment]
I merged in most of your changes, but tried to avoid the local_exec.lua and modifications to template.lua. For this I changed the name of the src dir to lgsl. I think it's better, as it also allows the user to do their own tests in the LuaJIT interpreter from the root of the repo directory, before/without installing the modules.

BTW: even numbers differ only a fraction of 1e-16, it can cause a difference in the %8g representation due to a rounding threshold that is just/just not reached....

**Comment by franko** [comment]
Hi Lesley,

Thank you for accepting the pull request.

As for the changes you have done, renaming to “src” directory to “lgsl” seems to be a good idea as it simplifies local testing, good! I need to figure out the details about package.path incantations you still need (I guess) but I suppose you just need to set a few variables in the testing script.

As for the python script to be honest I’m not really happy that you removed it to use a Lua script instead but that’s it, I guess this is not worth doing a confrontation ;)

As a practical point of view I was able to install luarocks on windows but impossible to install anything because of the proxy we have at work. Following the instructions here:

http://luarocks.org/en/LuaRocks_through_a_proxy

did not help and I’m no able to tell why it doesn’t work. I know that in principle it _should_ work because “git” is able to use the proxy using the environment variable `http_proxy` and `https_proxy`.

Otherwise that’s not a big problem. I guess on Linux everything will “just works” so at least I will be able to run the test suite on linux. That should be ok.

As for the potential issue with floating point numbers I’m not sure. My (naïve ?) idea was that format with `%g` was robust versus rounding issue but I’m not 100% sure. Maybe you can provide un example that illustrate the potential problem you are talking about.

**Comment by ladc** [comment]
Hi Francesco,

I've reinstated the python script so people can choose, if they must ;-)

It's very odd that Luarocks doesn't work. Could you check if it works if you change the rockspec url to something like "https://github.com/ladc/lgsl/archive/master.zip" instead of using the git:// protocol?

As for the floating point numbers, see an example here: https://gist.github.com/ladc/37f5f0ff2430750f80fb It seems quite convoluted, but I've encountered this problem quite often in real situations.

**Comment by franko** [comment]
Thank you for restoring the python script!

I guess that I can get luarocks working with the proxy but sometimes this is tricky to do so that’s no surprise that I have some problems.

For the moment it is already using some http address to download the manifest and I get the following errors:

```
C:\Users\francesco abbate>luarocks install lfs
Warning: Failed searching manifest: Failed fetching manifest for https://rocks.moonscript.org - Failed downloading https://rocks.moonscript.org/manifest
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/ - Failed downlo
ading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/ma
ster/manifest
Warning: Failed searching manifest: Failed fetching manifest for http://luafr.org/moonrocks/ - Failed downloading http://luafr.org/moonrocks/manifest
Warning: Failed searching manifest: Failed fetching manifest for http://luarocks.logiceditor.com/rocks - Failed downloading http://luarocks.logiceditor.com/rock
s/manifest

Error: No results matching query were found.
```

But I suggest that you don’t bother about that. I sure that if I persist long enough I will manage to find a solution.

I’m more interested to the issue with the number comparison. I see your example and now the problem you was pointing out is crystal clear. It happens when the remaining part after the required precision is very closed to 0.5 (up to a decimal exponential). In this case a very small difference can trigger a rounding in one direction or in the other one.

My idea is that while this is a problem in principle it can be ok from the practical point of view. This depend actually on how you configure the tests. The idea is that you should avoid of printing a lot of numbers with intermediate results but print only a very few numerical results obtained as the with some well-chosen calculations. For example in the NL fit I’m just printing only the final results on the fit and omitting all the intermediate results. By doing so there is virtually no chance to stumble on a rounding problem.

**Comment by ladc** [comment]
Note that although the module name is `lfs`, the full name of the package is `luafilesystem`.

**Pull request closed without merging**
